### ISSUE TITLE
No funciona kodi 18.5

### ISSUE THREAD

**Issue by methodmann** [josecurioso/repository.josecurioso.kodi#1]
Buenas, desde que actualice a kodi 18.5 no me encuentra ningun subtitulo el addon. Alguna solución? Gracias!!

**Comment by josecurioso** [comment]
Ya hace tiempo que no mantengo el addon simplemente porque personalmente no lo uso. Te enlazo al comentario que dejé hace unos días en el repo del addon [https://github.com/josecurioso2/service.subtitles.tusubtitulo/issues/5#issuecomment-574661870](https://github.com/josecurioso2/service.subtitles.tusubtitulo/issues/5#issuecomment-574661870) donde está el link a una nueva versión.
